### ISSUE TITLE
Copy generating code from Erlich's repo, put it in this repo, and cite him in the README

### ISSUE THREAD

**Issue by Apeirogons** [Apeirogons/NRGYorkU-Brain-Computer-Music-Interface#2]
https://github.com/stefan-ehrlich/code-algorithmicMusicGenerationSystem

**Comment by Apeirogons** [comment]
Harley

**Comment by hglassman** [comment]
Uploads are disabled.
File uploads require push access to this repository.

**Comment by Apeirogons** [comment]
Update: Unzipped the files and re-pushed (that's not really a git thing). I'm going to assign another issue, editing the README to incorporate any other project information that you'd like.

**Comment by hglassman** [comment]
Hey Matthew,

I have changed the files to include only zip. I realized that I originally
extracted it as unzipped files, but have since deleted them. Additionally,
the real-time zip file was added to the github folder. I will try to
include a readme of all the necessary components of project information
sometime next week before our meeting.

**Comment by Apeirogons** [comment]
For future reference, generally try for the unzipped files if the zip file contains code - we can't do very much with the zipped version of the code. I extracted the code and unzipped it (the point was just to make you commit something to GitHub)
